# importing module

import random

b = random.randint(1, 10)

# while Loop exicute Code until User guess the actual number which is generated by computer
while True:
    count = 0
    a = int(input("Enter the number:"))
    if a == b:
        print("Perfect guess")
        break
    else:
        print("wrong guess")


